### ISSUE TITLE
Segmentation fault error (python3.5)

### ISSUE THREAD

**Issue by rongfeng-china** [kitizz/edge3d-paper#1]
Building ray voxel grid
Making... 1150247 (1150247, 3)
Allocating raygrid. Mem: 0.31 Gb
Segmentation fault (core dumped)

**Comment by kitizz** [comment]
Hi! Thanks for taking a look at the project.
I think the issue was due to glob.glob not returning a properly sorted list of the image files on Ubuntu.
I've committed a fix to this, let me know if you have better luck :)

**Comment by rongfeng-china** [comment]
Thanks for your reply, and the problem still exists. 
I debugged and found the error was in RaySoup.py file "raygrid = RayGrid(80,center,size,30000)".
This error was originated from RayVoxel.py and the init function of class Grid. 
I guess some mistakes existed in the init function...

**Comment by kitizz** [comment]
Damn.
Are you using the accompanying datasets, or your own? I'll try to recreate it.
Bounds checks should be stopping this kind of thing from happening...

**Comment by rongfeng-china** [comment]
Yes, using the accompanying datasets.

**Comment by kitizz** [comment]
Could you uncomment the `@jitclass(_spec)` line in RayVoxel.py and let me know what happens?
Depending on what happens, can you then try to reduce RayGrid.Grid(80...) to RayGrid.Grid(40)?

And could you let me know what OS you're running, and how much RAM your machine has?

**Comment by kitizz** [comment]
Correction: "Could you comment out the `@jitclass(_spec)` ..."
